/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wfo;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Sudirwo
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        // Sesuaikan "/assets/nama_file.jpg" dengan nama file aslimu di package assets
        try {
            java.net.URL imgURL = getClass().getResource("/assets/wallpaper.jpeg");
            if (imgURL != null) {
                javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(imgURL);
                java.awt.Image imgSkala = iconAsli.getImage().getScaledInstance(1000, 700, java.awt.Image.SCALE_SMOOTH);
                lblBackground.setIcon(new javax.swing.ImageIcon(imgSkala));
            }
        } catch (Exception e) {
            System.out.println("Gagal memuat gambar: " + e.getMessage());
        }

        // Kode transparansi panel yang tadi (pastikan nama variabel sesuai)
        // Format: (Red, Green, Blue, Alpha) 
        // Alpha 0-255 (makin kecil makin transparan)   
        panelKiri.setBackground(new java.awt.Color(33, 33, 33, 200));        // Hitam transparan

        // Menambahkan waktu di panel Atas
        java.time.LocalDate tgl = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter format = java.time.format.DateTimeFormatter.ofPattern("dd MMM yyyy");
        lblTanggal.setText(tgl.format(format));
        
        // Menghilangkan background putih pada JTextArea
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0, 0)); 

        // Menghilangkan background dan border pada JScrollPane (wadahnya)
        paneText.setOpaque(false);
        paneText.getViewport().setOpaque(false);
        paneText.setBorder(null);
        paneText.setViewportBorder(null);
        
        // Atur skala/size
        aturSkala(instagramlogo, "/assets/instagram.png", 20, 20);
        aturSkala(anime, "/assets/kiriya aoi.png", 395, 533);
    }
    
    private void pindahMenu(String namaKartu) {
        java.awt.CardLayout card = (java.awt.CardLayout) panelUtama.getLayout();
        card.show(panelUtama, namaKartu);
        panelUtama.revalidate();
        panelUtama.repaint();
    }
    
    //atur size gambar jLabel
    private void aturSkala(javax.swing.JLabel label, String path, int w, int h) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelKiri = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JLabel();
        btnPC = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JLabel();
        btnAlarm = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        panelMenuBeranda = new javax.swing.JPanel();
        instagramlogo = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        paneText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        anime = new javax.swing.JLabel();
        panelMenuPC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelMenuPelanggan = new javax.swing.JPanel();
        btnBeranda6 = new javax.swing.JLabel();
        btnBeranda8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMenuTransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelMenuAlarm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logowfo.png"))); // NOI18N
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, -1, -1));

        panelHeader.setBackground(new java.awt.Color(0, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(1000, 80));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblAlamat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setText("Jl. Antara Ada dan Tiada, Desa Air, Banjarmasin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date :");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(lblAlamat)
                .addGap(175, 175, 175)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlamat)
                .addGap(23, 23, 23))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        panelKiri.setBackground(new java.awt.Color(153, 153, 153));

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_off.png"))); // NOI18N
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
        });

        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_off.png"))); // NOI18N
        btnPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPCMouseExited(evt);
            }
        });

        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_off.png"))); // NOI18N
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPelangganMouseExited(evt);
            }
        });

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_off.png"))); // NOI18N
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_off.png"))); // NOI18N
        btnAlarm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlarmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlarmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlarmMouseExited(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_logout_off.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                            .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAlarm)
                                .addComponent(btnLogout))
                            .addGap(24, 24, 24)))
                    .addComponent(btnPC)
                    .addComponent(btnPelanggan)
                    .addComponent(btnTransaksi))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBeranda)
                .addGap(18, 18, 18)
                .addComponent(btnPC)
                .addGap(18, 18, 18)
                .addComponent(btnPelanggan)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi)
                .addGap(55, 55, 55)
                .addComponent(btnAlarm)
                .addGap(67, 67, 67)
                .addComponent(btnLogout)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        getContentPane().add(panelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 620));

        panelUtama.setBackground(new java.awt.Color(63, 63, 63));
        panelUtama.setLayout(new java.awt.CardLayout());

        panelMenuBeranda.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instagramlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instagram.png"))); // NOI18N
        panelMenuBeranda.add(instagramlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 20, 20));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("SELAMAT DATANG!!");
        panelMenuBeranda.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 53, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Di sini menyediakan penyewaan PC dengan harga yang terjangkau se-Banjarmasin.\n\nMau :\n- Ngegame\n- Internetan\n- Nugas\n- Ngetik\ndan lain-lain.\n\nWFO tempatnya. Yuk ramaikan keseruanmu di sosial media, dan tag\n        @WarnetFO\n\nKami usahakan memberikan pelayanan yang terbaik. Anda sopan kami senang.\nTerima kasih\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        paneText.setViewportView(jTextArea1);

        panelMenuBeranda.add(paneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 103, 651, 348));
        panelMenuBeranda.add(anime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 395, 533));

        panelUtama.add(panelMenuBeranda, "menu_beranda");

        panelMenuPC.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA PC");

        javax.swing.GroupLayout panelMenuPCLayout = new javax.swing.GroupLayout(panelMenuPC);
        panelMenuPC.setLayout(panelMenuPCLayout);
        panelMenuPCLayout.setHorizontalGroup(
            panelMenuPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPCLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addContainerGap(596, Short.MAX_VALUE))
        );
        panelMenuPCLayout.setVerticalGroup(
            panelMenuPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPCLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuPC, "menu_pc");

        panelMenuPelanggan.setBackground(new java.awt.Color(51, 51, 51));

        btnBeranda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihalarm_off.png"))); // NOI18N
        btnBeranda6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBeranda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihtr_off.png"))); // NOI18N
        btnBeranda8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PELANGGAN");

        javax.swing.GroupLayout panelMenuPelangganLayout = new javax.swing.GroupLayout(panelMenuPelanggan);
        panelMenuPelanggan.setLayout(panelMenuPelangganLayout);
        panelMenuPelangganLayout.setHorizontalGroup(
            panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                .addComponent(btnBeranda8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                .addGroup(panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnBeranda6))
                    .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)))
                .addGap(0, 564, Short.MAX_VALUE))
        );
        panelMenuPelangganLayout.setVerticalGroup(
            panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPelangganLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addGroup(panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBeranda6)
                    .addComponent(btnBeranda8))
                .addGap(111, 111, 111))
        );

        panelUtama.add(panelMenuPelanggan, "menu_pelanggan");

        panelMenuTransaksi.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRANSAKSI");

        javax.swing.GroupLayout panelMenuTransaksiLayout = new javax.swing.GroupLayout(panelMenuTransaksi);
        panelMenuTransaksi.setLayout(panelMenuTransaksiLayout);
        panelMenuTransaksiLayout.setHorizontalGroup(
            panelMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTransaksiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        panelMenuTransaksiLayout.setVerticalGroup(
            panelMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTransaksiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuTransaksi, "menu_transaksi");

        panelMenuAlarm.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALARM");

        javax.swing.GroupLayout panelMenuAlarmLayout = new javax.swing.GroupLayout(panelMenuAlarm);
        panelMenuAlarm.setLayout(panelMenuAlarmLayout);
        panelMenuAlarmLayout.setHorizontalGroup(
            panelMenuAlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAlarmLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        panelMenuAlarmLayout.setVerticalGroup(
            panelMenuAlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAlarmLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuAlarm, "menu_alarm");

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 790, 620));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_beranda");
    }//GEN-LAST:event_btnBerandaMouseClicked

    private void btnPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_pc");
    }//GEN-LAST:event_btnPCMouseClicked

    private void btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_pelanggan");
    }//GEN-LAST:event_btnPelangganMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_transaksi");
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnAlarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_alarm");
    }//GEN-LAST:event_btnAlarmMouseClicked

    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered
        // TODO add your handling code here:
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnBeranda.repaint();
    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited
        // TODO add your handling code here:
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_off.png")));
        btnBeranda.repaint();
    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseEntered
        // TODO add your handling code here:
        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnPC.repaint();
    }//GEN-LAST:event_btnPCMouseEntered

    private void btnPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseExited
        // TODO add your handling code here:
        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_off.png")));
        btnPC.repaint();
    }//GEN-LAST:event_btnPCMouseExited

    private void btnPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseEntered
        // TODO add your handling code here:
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnPelanggan.repaint();
    }//GEN-LAST:event_btnPelangganMouseEntered

    private void btnPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseExited
        // TODO add your handling code here:
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_off.png")));
        btnPelanggan.repaint();
    }//GEN-LAST:event_btnPelangganMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        // TODO add your handling code here:
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnTransaksi.repaint();
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_off.png")));
        btnTransaksi.repaint();
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnAlarmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseEntered
        // TODO add your handling code here:
        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnAlarm.repaint();
    }//GEN-LAST:event_btnAlarmMouseEntered

    private void btnAlarmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseExited
        // TODO add your handling code here:
        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_off.png")));
        btnAlarm.repaint();
    }//GEN-LAST:event_btnAlarmMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anime;
    private javax.swing.JLabel btnAlarm;
    private javax.swing.JLabel btnBeranda;
    private javax.swing.JLabel btnBeranda6;
    private javax.swing.JLabel btnBeranda8;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPC;
    private javax.swing.JLabel btnPelanggan;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JLabel instagramlogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane paneText;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelMenuAlarm;
    private javax.swing.JPanel panelMenuBeranda;
    private javax.swing.JPanel panelMenuPC;
    private javax.swing.JPanel panelMenuPelanggan;
    private javax.swing.JPanel panelMenuTransaksi;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
