/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wfo;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; // Untuk notifikasi sederhana
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sudirwo
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        // Sesuaikan "/assets/nama_file.jpg" dengan nama file aslimu di package assets
        try {
            java.net.URL imgURL = getClass().getResource("/assets/wallpaper.jpeg");
            if (imgURL != null) {
                javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(imgURL);
                java.awt.Image imgSkala = iconAsli.getImage().getScaledInstance(1000, 700, java.awt.Image.SCALE_SMOOTH);
                lblBackground.setIcon(new javax.swing.ImageIcon(imgSkala));
            }
        } catch (Exception e) {
            System.out.println("Gagal memuat gambar: " + e.getMessage());
        }

        // Kode transparansi panel yang tadi (pastikan nama variabel sesuai)
        // Format: (Red, Green, Blue, Alpha) 
        // Alpha 0-255 (makin kecil makin transparan)   
        panelKiri.setBackground(new java.awt.Color(33, 33, 33, 200));        // Hitam transparan

        // Menambahkan waktu di panel Atas
        java.time.LocalDate tgl = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter format = java.time.format.DateTimeFormatter.ofPattern("dd MMM yyyy");
        lblTanggal.setText(tgl.format(format));
        
        // Menghilangkan background putih pada JTextArea
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0, 0)); 

        // Menghilangkan background dan border pada JScrollPane (wadahnya)
        paneText.setOpaque(false);
        paneText.getViewport().setOpaque(false);
        paneText.setBorder(null);
        paneText.setViewportBorder(null);
        
        // Atur skala/size
        aturSkala(instagramlogo, "/assets/instagram.png", 20, 20);
        aturSkala(anime, "/assets/kiriya aoi.png", 395, 533);
        
        // Menambah data dummy ke tabel
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();
    
        // BARIS SAKTI: Menghapus semua baris bawaan NetBeans yang kosong
        model.setRowCount(0); 

        // Baru kemudian isi data dummy
        model.addRow(new Object[]{"PC26001", "Asus", "Intel i5", "10000"});
        model.addRow(new Object[]{"PC26002", "Acer", "Intel i3", "8000"});
        
        //tabel pelanggan
        DefaultTableModel modelP = (DefaultTableModel) tabelPL.getModel();
        modelP.setRowCount(0); // Membersihkan baris kosong bawaan
        modelP.addRow(new Object[]{"PLG001", "Adinata", "Laki-laki", "0812345678", "Jl. Jalan Didu Tamol, Banjarmasin", "adiadita@gmail.com"});
    }
    
    //*-----------------ini luar constructor
    
    private void pindahMenu(String namaKartu) {
        java.awt.CardLayout card = (java.awt.CardLayout) panelUtama.getLayout();
        card.show(panelUtama, namaKartu);
        panelUtama.revalidate();
        panelUtama.repaint();
    }
    
    //atur size gambar jLabel
    private void aturSkala(javax.swing.JLabel label, String path, int w, int h) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelKiri = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JLabel();
        btnPC = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JLabel();
        btnAlarm = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        panelMenuBeranda = new javax.swing.JPanel();
        instagramlogo = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        paneText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        anime = new javax.swing.JLabel();
        panelMenuPC = new javax.swing.JPanel();
        judulPC = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtMerek = new javax.swing.JTextField();
        txtProcessor = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPC = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtPCCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPilih = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTarif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelMenuPelanggan = new javax.swing.JPanel();
        judulPl = new javax.swing.JLabel();
        head1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPlID = new javax.swing.JTextField();
        txtPlNama = new javax.swing.JTextField();
        cmbPlGender = new javax.swing.JComboBox<>();
        txtPlTelpon = new javax.swing.JTextField();
        txtPlAlamat = new javax.swing.JTextField();
        txtPlEmail = new javax.swing.JTextField();
        btnPlCetak = new javax.swing.JButton();
        btnPlDaftar = new javax.swing.JButton();
        btnPlEdit = new javax.swing.JButton();
        btnPlHapus = new javax.swing.JButton();
        btnPlBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPL = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtPlCari = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnPlPilih = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelMenuTransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelMenuAlarm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelMenuPC1 = new javax.swing.JPanel();
        jdlTransaksi = new javax.swing.JLabel();
        head2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        txtMerek1 = new javax.swing.JTextField();
        txtProcessor1 = new javax.swing.JTextField();
        btnCetak1 = new javax.swing.JButton();
        btnDaftar1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelPC1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        txtPCCari1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btnPilih1 = new javax.swing.JLabel();
        btnBatal1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtTarif1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logowfo.png"))); // NOI18N
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, -1, -1));

        panelHeader.setBackground(new java.awt.Color(0, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(1000, 80));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblAlamat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setText("Jl. Antara Ada dan Tiada, Desa Air, Banjarmasin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date :");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(lblAlamat)
                .addGap(148, 148, 148)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlamat)
                .addGap(26, 26, 26))
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        panelKiri.setBackground(new java.awt.Color(153, 153, 153));

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_off.png"))); // NOI18N
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
        });

        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_off.png"))); // NOI18N
        btnPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPCMouseExited(evt);
            }
        });

        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_off.png"))); // NOI18N
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPelangganMouseExited(evt);
            }
        });

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_off.png"))); // NOI18N
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_off.png"))); // NOI18N
        btnAlarm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlarmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlarmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlarmMouseExited(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_logout_off.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                            .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAlarm)
                                .addComponent(btnLogout))
                            .addGap(24, 24, 24)))
                    .addComponent(btnPC)
                    .addComponent(btnPelanggan)
                    .addComponent(btnTransaksi))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBeranda)
                .addGap(18, 18, 18)
                .addComponent(btnPC)
                .addGap(18, 18, 18)
                .addComponent(btnPelanggan)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi)
                .addGap(55, 55, 55)
                .addComponent(btnAlarm)
                .addGap(67, 67, 67)
                .addComponent(btnLogout)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        getContentPane().add(panelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 620));

        panelUtama.setBackground(new java.awt.Color(63, 63, 63));
        panelUtama.setLayout(new java.awt.CardLayout());

        panelMenuBeranda.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instagramlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instagram.png"))); // NOI18N
        panelMenuBeranda.add(instagramlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 20, 20));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("SELAMAT DATANG!!");
        panelMenuBeranda.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 53, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Di sini menyediakan penyewaan PC dengan harga yang terjangkau se-Banjarmasin.\n\nMau :\n- Ngegame\n- Internetan\n- Nugas\n- Ngetik\ndan lain-lain.\n\nWFO tempatnya. Yuk ramaikan keseruanmu di sosial media, dan tag\n        @WarnetFO\n\nKami usahakan memberikan pelayanan yang terbaik. Anda sopan kami senang.\nTerima kasih\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        paneText.setViewportView(jTextArea1);

        panelMenuBeranda.add(paneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 103, 651, 348));
        panelMenuBeranda.add(anime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 395, 533));

        panelUtama.add(panelMenuBeranda, "menu_beranda");

        panelMenuPC.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuPC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulPC.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        judulPC.setForeground(new java.awt.Color(255, 255, 255));
        judulPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPC.setText("DATA PC");
        panelMenuPC.add(judulPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 20, 200, 50));

        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/head.png"))); // NOI18N
        panelMenuPC.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID :");
        panelMenuPC.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 150, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Merek :");
        panelMenuPC.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Processor :");
        panelMenuPC.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        panelMenuPC.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, -1));

        txtMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMerekActionPerformed(evt);
            }
        });
        panelMenuPC.add(txtMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 250, -1));
        panelMenuPC.add(txtProcessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 250, -1));

        btnCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMenuPC.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 80, 30));

        btnDaftar.setBackground(new java.awt.Color(51, 102, 255));
        btnDaftar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/person_add.png"))); // NOI18N
        btnDaftar.setText("Daftar");
        btnDaftar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarMouseClicked(evt);
            }
        });
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        panelMenuPC.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, 150, 20));

        btnEdit.setBackground(new java.awt.Color(51, 102, 255));
        btnEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 231, 150, 20));

        btnHapus.setBackground(new java.awt.Color(51, 102, 255));
        btnHapus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buang.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 231, 150, 20));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Merek", "Processor", "Tarif"
            }
        ));
        tabelPC.setFillsViewportHeight(true);
        tabelPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPC);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 150));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cari PC :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        txtPCCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPCCariActionPerformed(evt);
            }
        });
        txtPCCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPCCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtPCCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 20));

        panelMenuPC.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 660, 200));

        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihtr_off.png"))); // NOI18N
        btnPilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btnBatal.setBackground(new java.awt.Color(51, 102, 255));
        btnBatal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 231, 150, 20));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Tarif / jam :");
        panelMenuPC.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 150, -1));

        txtTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifActionPerformed(evt);
            }
        });
        txtTarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifKeyTyped(evt);
            }
        });
        panelMenuPC.add(txtTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        panelMenuPC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, 30));

        panelUtama.add(panelMenuPC, "menu_pc");

        panelMenuPelanggan.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuPelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulPl.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        judulPl.setForeground(new java.awt.Color(255, 255, 255));
        judulPl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPl.setText("PELANGGAN");
        panelMenuPelanggan.add(judulPl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 20, 200, 50));

        head1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/head.png"))); // NOI18N
        panelMenuPelanggan.add(head1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ID Pelanggan  :");
        panelMenuPelanggan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("No. Telpon   :");
        panelMenuPelanggan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 110, -1));

        txtPlID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlIDActionPerformed(evt);
            }
        });
        panelMenuPelanggan.add(txtPlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, -1));

        txtPlNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlNamaActionPerformed(evt);
            }
        });
        panelMenuPelanggan.add(txtPlNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 580, -1));

        cmbPlGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "Laki-laki", "Perempuan" }));
        panelMenuPelanggan.add(cmbPlGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 210, -1));

        txtPlTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlTelponActionPerformed(evt);
            }
        });
        txtPlTelpon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlTelponKeyTyped(evt);
            }
        });
        panelMenuPelanggan.add(txtPlTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 160, -1));

        txtPlAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlAlamatActionPerformed(evt);
            }
        });
        txtPlAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlAlamatKeyTyped(evt);
            }
        });
        panelMenuPelanggan.add(txtPlAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 580, -1));
        panelMenuPelanggan.add(txtPlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 310, -1));

        btnPlCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnPlCetak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlCetak.setText("Cetak");
        btnPlCetak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMenuPelanggan.add(btnPlCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 80, 30));

        btnPlDaftar.setBackground(new java.awt.Color(51, 102, 255));
        btnPlDaftar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnPlDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/person_add.png"))); // NOI18N
        btnPlDaftar.setText("Daftar");
        btnPlDaftar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlDaftarMouseClicked(evt);
            }
        });
        btnPlDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlDaftarActionPerformed(evt);
            }
        });
        panelMenuPelanggan.add(btnPlDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, 150, 20));

        btnPlEdit.setBackground(new java.awt.Color(51, 102, 255));
        btnPlEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnPlEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        btnPlEdit.setText("Edit");
        btnPlEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlEditMouseClicked(evt);
            }
        });
        panelMenuPelanggan.add(btnPlEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 231, 150, 20));

        btnPlHapus.setBackground(new java.awt.Color(51, 102, 255));
        btnPlHapus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buang.png"))); // NOI18N
        btnPlHapus.setText("Hapus");
        btnPlHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlHapusMouseClicked(evt);
            }
        });
        panelMenuPelanggan.add(btnPlHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 231, 150, 20));

        btnPlBatal.setBackground(new java.awt.Color(51, 102, 255));
        btnPlBatal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnPlBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/batal.png"))); // NOI18N
        btnPlBatal.setText("Batal");
        btnPlBatal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlBatalMouseClicked(evt);
            }
        });
        panelMenuPelanggan.add(btnPlBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 231, 150, 20));

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "No. Telp.", "Alamat", "Email"
            }
        ));
        tabelPL.setFillsViewportHeight(true);
        tabelPL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPLMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPL);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 150));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Cari PC :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        txtPlCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlCariActionPerformed(evt);
            }
        });
        txtPlCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlCariKeyReleased(evt);
            }
        });
        jPanel2.add(txtPlCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 260, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 20));

        panelMenuPelanggan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 660, 200));

        btnPlPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihtr_off.png"))); // NOI18N
        btnPlPilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlPilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlPilihMouseClicked(evt);
            }
        });
        panelMenuPelanggan.add(btnPlPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Alamat  :");
        panelMenuPelanggan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        panelMenuPelanggan.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Nama Lengkap  :");
        panelMenuPelanggan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Jenis Kelamin  :");
        panelMenuPelanggan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Email  :");
        panelMenuPelanggan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, -1));

        panelUtama.add(panelMenuPelanggan, "menu_pelanggan");

        panelMenuTransaksi.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRANSAKSI");

        javax.swing.GroupLayout panelMenuTransaksiLayout = new javax.swing.GroupLayout(panelMenuTransaksi);
        panelMenuTransaksi.setLayout(panelMenuTransaksiLayout);
        panelMenuTransaksiLayout.setHorizontalGroup(
            panelMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTransaksiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        panelMenuTransaksiLayout.setVerticalGroup(
            panelMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTransaksiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuTransaksi, "menu_transaksi3");

        panelMenuAlarm.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALARM");

        javax.swing.GroupLayout panelMenuAlarmLayout = new javax.swing.GroupLayout(panelMenuAlarm);
        panelMenuAlarm.setLayout(panelMenuAlarmLayout);
        panelMenuAlarmLayout.setHorizontalGroup(
            panelMenuAlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAlarmLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        panelMenuAlarmLayout.setVerticalGroup(
            panelMenuAlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAlarmLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuAlarm, "menu_alarm");

        panelMenuPC1.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuPC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdlTransaksi.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jdlTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jdlTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jdlTransaksi.setText("TRANSAKSI");
        panelMenuPC1.add(jdlTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 20, 200, 50));

        head2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/head.png"))); // NOI18N
        panelMenuPC1.add(head2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ID :");
        panelMenuPC1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 150, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Merek :");
        panelMenuPC1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Processor :");
        panelMenuPC1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, -1));

        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        panelMenuPC1.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, -1));

        txtMerek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMerek1ActionPerformed(evt);
            }
        });
        panelMenuPC1.add(txtMerek1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 250, -1));
        panelMenuPC1.add(txtProcessor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 250, -1));

        btnCetak1.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCetak1.setText("Cetak");
        btnCetak1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMenuPC1.add(btnCetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 80, 30));

        btnDaftar1.setBackground(new java.awt.Color(51, 102, 255));
        btnDaftar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDaftar1.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/person_add.png"))); // NOI18N
        btnDaftar1.setText("Daftar");
        btnDaftar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDaftar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftar1MouseClicked(evt);
            }
        });
        btnDaftar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftar1ActionPerformed(evt);
            }
        });
        panelMenuPC1.add(btnDaftar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, 150, 20));

        btnEdit1.setBackground(new java.awt.Color(51, 102, 255));
        btnEdit1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        btnEdit1.setText("Edit");
        btnEdit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdit1MouseClicked(evt);
            }
        });
        panelMenuPC1.add(btnEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 231, 150, 20));

        btnHapus1.setBackground(new java.awt.Color(51, 102, 255));
        btnHapus1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnHapus1.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buang.png"))); // NOI18N
        btnHapus1.setText("Hapus");
        btnHapus1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapus1MouseClicked(evt);
            }
        });
        panelMenuPC1.add(btnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 231, 150, 20));

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPC1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Merek", "Processor", "Tarif"
            }
        ));
        tabelPC1.setFillsViewportHeight(true);
        tabelPC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPC1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelPC1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 150));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Cari PC :");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        txtPCCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPCCari1ActionPerformed(evt);
            }
        });
        txtPCCari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPCCari1KeyReleased(evt);
            }
        });
        jPanel3.add(txtPCCari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 260, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 20));

        panelMenuPC1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 660, 200));

        btnPilih1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihtr_off.png"))); // NOI18N
        btnPilih1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilih1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilih1MouseClicked(evt);
            }
        });
        panelMenuPC1.add(btnPilih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btnBatal1.setBackground(new java.awt.Color(51, 102, 255));
        btnBatal1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBatal1.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/batal.png"))); // NOI18N
        btnBatal1.setText("Batal");
        btnBatal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBatal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatal1MouseClicked(evt);
            }
        });
        panelMenuPC1.add(btnBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 231, 150, 20));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Tarif / jam :");
        panelMenuPC1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 150, -1));

        txtTarif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarif1ActionPerformed(evt);
            }
        });
        txtTarif1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarif1KeyTyped(evt);
            }
        });
        panelMenuPC1.add(txtTarif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 250, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        panelMenuPC1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, 30));

        panelUtama.add(panelMenuPC1, "menu_transaksi");

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 790, 620));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_beranda");
    }//GEN-LAST:event_btnBerandaMouseClicked

    private void btnPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_pc");
    }//GEN-LAST:event_btnPCMouseClicked

    private void btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_pelanggan");
    }//GEN-LAST:event_btnPelangganMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_transaksi");
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnAlarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_alarm");
    }//GEN-LAST:event_btnAlarmMouseClicked

    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered
        // TODO add your handling code here:
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnBeranda.repaint();
    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited
        // TODO add your handling code here:
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_off.png")));
        btnBeranda.repaint();
    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseEntered
        // TODO add your handling code here:
        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnPC.repaint();
    }//GEN-LAST:event_btnPCMouseEntered

    private void btnPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseExited
        // TODO add your handling code here:
        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_off.png")));
        btnPC.repaint();
    }//GEN-LAST:event_btnPCMouseExited

    private void btnPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseEntered
        // TODO add your handling code here:
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnPelanggan.repaint();
    }//GEN-LAST:event_btnPelangganMouseEntered

    private void btnPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseExited
        // TODO add your handling code here:
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_off.png")));
        btnPelanggan.repaint();
    }//GEN-LAST:event_btnPelangganMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        // TODO add your handling code here:
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnTransaksi.repaint();
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_off.png")));
        btnTransaksi.repaint();
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnAlarmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseEntered
        // TODO add your handling code here:
        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnAlarm.repaint();
    }//GEN-LAST:event_btnAlarmMouseEntered

    private void btnAlarmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseExited
        // TODO add your handling code here:
        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_off.png")));
        btnAlarm.repaint();
    }//GEN-LAST:event_btnAlarmMouseExited

    private void txtPCCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPCCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPCCariActionPerformed

    private void txtTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerekActionPerformed

    private void tabelPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPCMouseClicked
        // TODO add your handling code here:
        int baris = tabelPC.getSelectedRow();
    
        // Penjaga: Jika baris yang diklik valid (bukan -1) 
        // dan datanya tidak kosong
        if (baris != -1 && tabelPC.getValueAt(baris, 0) != null) {
            try {
                txtID.setText(tabelPC.getValueAt(baris, 0).toString());
                txtMerek.setText(tabelPC.getValueAt(baris, 1).toString());
                txtProcessor.setText(tabelPC.getValueAt(baris, 2).toString());
                txtTarif.setText(tabelPC.getValueAt(baris, 3).toString());
            } catch (Exception e) {
                // Jika ada error tipe data, aplikasi tidak akan crash
                System.out.println("Error klik tabel: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_tabelPCMouseClicked

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseClicked
        // TODO add your handling code here:
        // Validasi: Cek apakah SEMUA field kosong (0/4)
        if (txtID.getText().isEmpty() && txtMerek.getText().isEmpty() && 
            txtProcessor.getText().isEmpty() && txtTarif.getText().isEmpty()) {

            // Jika 0/4 diisi, munculkan peringatan
            JOptionPane.showMessageDialog(this, "Minimal isi salah satu data (ID, Merek, Processor, atau Tarif)!", "Peringatan", JOptionPane.WARNING_MESSAGE);

        } else {
            // Jika minimal 1/4 diisi, data masuk ke tabel
            DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();
            model.addRow(new Object[]{
                txtID.getText(), 
                txtMerek.getText(), 
                txtProcessor.getText(), 
                txtTarif.getText()
            });

            JOptionPane.showMessageDialog(this, "Data PC Berhasil Didaftarkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Opsional: Kosongkan field setelah daftar agar bisa input data baru
            btnBatalMouseClicked(null); 
        }
    }//GEN-LAST:event_btnDaftarMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        int i = tabelPC.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();

        if (i >= 0) {
            model.setValueAt(txtID.getText(), i, 0);
            model.setValueAt(txtMerek.getText(), i, 1);
            model.setValueAt(txtProcessor.getText(), i, 2);
            model.setValueAt(txtTarif.getText(), i, 3);

            JOptionPane.showMessageDialog(this, "Data PC Berhasil Diperbarui!", "Update Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit di tabel terlebih dahulu!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        int i = tabelPC.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();

        if (i >= 0) {
            // Tanya konfirmasi
            int tanya = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data PC ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (tanya == JOptionPane.YES_OPTION) {
                model.removeRow(i);
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus.");
                btnBatalMouseClicked(null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        txtID.setText("");
        txtMerek.setText("");
        txtProcessor.setText("");
        txtTarif.setText("");
        tabelPC.clearSelection();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnPilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMouseClicked
        // TODO add your handling code here:
        /*if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih data PC terlebih dahulu!");
        } else {
            // 1. Ambil data dari textfield
            String idTerpilih = txtID.getText();
            String tarifTerpilih = txtTarif.getText();

            // 2. Set ke Label di Laman Transaksi (Asumsi nama variabel label di Laman Transaksi)
            lblIDTransaksi.setText(idTerpilih);
            lblTarifTransaksi.setText(tarifTerpilih);

            // 3. Pindah ke Laman Transaksi
            java.awt.CardLayout card = (java.awt.CardLayout) panelUtama.getLayout();
            card.show(panelUtama, "kartu_transaksi");

            // Jangan lupa reset tombol sidebar agar sesuai menu yang aktif
            resetTombol();
            btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_on.png")));
        }
        */
    }//GEN-LAST:event_btnPilihMouseClicked

    private void txtTarifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
    
        // Cek jika yang diketik bukan angka DAN bukan tombol hapus
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Hapus inputannya

            // Munculkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Input salah! Kolom Tarif hanya boleh diisi dengan angka.", "Peringatan Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtTarifKeyTyped

    private void txtPlIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlIDActionPerformed

    private void txtPlNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlNamaActionPerformed

    private void btnPlDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlDaftarMouseClicked
        // TODO add your handling code here:
        String nama = txtPlNama.getText();
        String telp = txtPlTelpon.getText();
        int indexGender = cmbPlGender.getSelectedIndex();

        if (nama.isEmpty() || telp.isEmpty() || indexGender == 0) {
            JOptionPane.showMessageDialog(this, "Nama, No. Telpon, dan Gender wajib diisi!");
        } 
        // CEK DUPLIKAT BERDASARKAN NAMA & TELP
        else if (isPelangganExist(nama, telp)) { 
            JOptionPane.showMessageDialog(this, "Pelanggan dengan Nama dan No. Telpon ini sudah terdaftar!", "Data Ganda", JOptionPane.ERROR_MESSAGE);
        } 
        else if (telp.length() < 11) {
            JOptionPane.showMessageDialog(this, "Nomor Telpon minimal 11 angka!");
        } 
        else {
            // PROSES SIMPAN...
            DefaultTableModel model = (DefaultTableModel) tabelPL.getModel();
            model.addRow(new Object[]{
                "AUTO", // Sementara tulis AUTO karena nanti di SQL ini otomatis
                nama,
                cmbPlGender.getSelectedItem().toString(),
                telp,
                txtPlAlamat.getText(),
                txtPlEmail.getText()
            });
            JOptionPane.showMessageDialog(this, "Pelanggan Berhasil Didaftarkan!");
            btnPlBatalMouseClicked(null); 
        }
       
    }//GEN-LAST:event_btnPlDaftarMouseClicked

    private void btnPlDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlDaftarActionPerformed

    private void btnPlEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlEditMouseClicked
        // TODO add your handling code here:
        int i = tabelPL.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelPL.getModel();

        if (i != -1) {
            model.setValueAt(txtPlID.getText(), i, 0);
            model.setValueAt(txtPlNama.getText(), i, 1);
            model.setValueAt(cmbPlGender.getSelectedItem().toString(), i, 2);
            model.setValueAt(txtPlTelpon.getText(), i, 3);
            model.setValueAt(txtPlAlamat.getText(), i, 4);
            model.setValueAt(txtPlEmail.getText(), i, 5);

            JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Diperbarui!");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih pelanggan di tabel yang ingin diedit!");
        }
    }//GEN-LAST:event_btnPlEditMouseClicked

    private void btnPlHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlHapusMouseClicked
        // TODO add your handling code here:
        int i = tabelPL.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelPL.getModel();

        if (i != -1) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus data pelanggan: " + txtPlNama.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                model.removeRow(i);
                JOptionPane.showMessageDialog(this, "Data telah dihapus.");
                btnPlBatalMouseClicked(null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus pada tabel!");
        }
    }//GEN-LAST:event_btnPlHapusMouseClicked

    private void tabelPLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPLMouseClicked
        // TODO add your handling code here:
        int i = tabelPL.getSelectedRow();
        if (i != -1 && tabelPL.getValueAt(i, 0) != null) {
            txtPlID.setText(tabelPL.getValueAt(i, 0).toString());
            txtPlNama.setText(tabelPL.getValueAt(i, 1).toString());
            cmbPlGender.setSelectedItem(tabelPL.getValueAt(i, 2).toString());
            txtPlTelpon.setText(tabelPL.getValueAt(i, 3).toString());
            txtPlAlamat.setText(tabelPL.getValueAt(i, 4).toString());
            txtPlEmail.setText(tabelPL.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_tabelPLMouseClicked

    private void txtPlCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlCariActionPerformed

    private void btnPlPilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlPilihMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlPilihMouseClicked

    private void btnPlBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlBatalMouseClicked
        // TODO add your handling code here:
        txtPlID.setText("");
        txtPlNama.setText("");
        txtPlTelpon.setText("");
        txtPlAlamat.setText("");
        txtPlEmail.setText("");
        cmbPlGender.setSelectedIndex(0);
        tabelPL.clearSelection();
 
    }//GEN-LAST:event_btnPlBatalMouseClicked

    private void txtPlAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlAlamatActionPerformed

    private void txtPlAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlAlamatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlAlamatKeyTyped

    private void txtPlTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlTelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlTelponActionPerformed

    private void txtPlTelponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlTelponKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            
            // Munculkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Input salah! Kolom Tarif hanya boleh diisi dengan angka.", "Peringatan Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPlTelponKeyTyped

    private void txtPlCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelPL.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tabelPL.setRowSorter(sorter);

        // Ini akan mencari di semua kolom (ID, Nama, Telpon, dll) sekaligus
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtPlCari.getText()));
    }//GEN-LAST:event_txtPlCariKeyReleased

    private void txtPCCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tabelPC.setRowSorter(sorter);

        // "(?i)" artinya Case Insensitive (tidak peduli huruf besar/kecil)
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtPCCari.getText()));
    }//GEN-LAST:event_txtPCCariKeyReleased

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void txtMerek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMerek1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerek1ActionPerformed

    private void btnDaftar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftar1MouseClicked

    private void btnDaftar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftar1ActionPerformed

    private void btnEdit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1MouseClicked

    private void btnHapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapus1MouseClicked

    private void tabelPC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPC1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelPC1MouseClicked

    private void txtPCCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPCCari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPCCari1ActionPerformed

    private void txtPCCari1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCCari1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPCCari1KeyReleased

    private void btnPilih1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilih1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPilih1MouseClicked

    private void btnBatal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatal1MouseClicked

    private void txtTarif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarif1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarif1ActionPerformed

    private void txtTarif1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarif1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarif1KeyTyped
    //buat menghindari duplikasi data di tabel pelanggan
    private boolean isPelangganExist(String namaBaru, String telpBaru) {
        for (int i = 0; i < tabelPL.getRowCount(); i++) {
            String namaDiTabel = tabelPL.getValueAt(i, 1).toString();
            String telpDiTabel = tabelPL.getValueAt(i, 3).toString();

            // Cek apakah Nama DAN No Telp sama persis dengan yang ada di tabel
            if (namaDiTabel.equalsIgnoreCase(namaBaru) && telpDiTabel.equals(telpBaru)) {
                return true; // Data orang ini sudah ada!
            }
        }
        return false;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anime;
    private javax.swing.JLabel btnAlarm;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JLabel btnBeranda;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnCetak1;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnDaftar1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPC;
    private javax.swing.JLabel btnPelanggan;
    private javax.swing.JLabel btnPilih;
    private javax.swing.JLabel btnPilih1;
    private javax.swing.JButton btnPlBatal;
    private javax.swing.JButton btnPlCetak;
    private javax.swing.JButton btnPlDaftar;
    private javax.swing.JButton btnPlEdit;
    private javax.swing.JButton btnPlHapus;
    private javax.swing.JLabel btnPlPilih;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JComboBox<String> cmbPlGender;
    private javax.swing.JLabel head;
    private javax.swing.JLabel head1;
    private javax.swing.JLabel head2;
    private javax.swing.JLabel instagramlogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jdlTransaksi;
    private javax.swing.JLabel judulPC;
    private javax.swing.JLabel judulPl;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane paneText;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelMenuAlarm;
    private javax.swing.JPanel panelMenuBeranda;
    private javax.swing.JPanel panelMenuPC;
    private javax.swing.JPanel panelMenuPC1;
    private javax.swing.JPanel panelMenuPelanggan;
    private javax.swing.JPanel panelMenuTransaksi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tabelPC;
    private javax.swing.JTable tabelPC1;
    private javax.swing.JTable tabelPL;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtMerek1;
    private javax.swing.JTextField txtPCCari;
    private javax.swing.JTextField txtPCCari1;
    private javax.swing.JTextField txtPlAlamat;
    private javax.swing.JTextField txtPlCari;
    private javax.swing.JTextField txtPlEmail;
    private javax.swing.JTextField txtPlID;
    private javax.swing.JTextField txtPlNama;
    private javax.swing.JTextField txtPlTelpon;
    private javax.swing.JTextField txtProcessor;
    private javax.swing.JTextField txtProcessor1;
    private javax.swing.JTextField txtTarif;
    private javax.swing.JTextField txtTarif1;
    // End of variables declaration//GEN-END:variables
}
