/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wfo;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; // Untuk notifikasi sederhana

/**
 *
 * @author Sudirwo
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        // Sesuaikan "/assets/nama_file.jpg" dengan nama file aslimu di package assets
        try {
            java.net.URL imgURL = getClass().getResource("/assets/wallpaper.jpeg");
            if (imgURL != null) {
                javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(imgURL);
                java.awt.Image imgSkala = iconAsli.getImage().getScaledInstance(1000, 700, java.awt.Image.SCALE_SMOOTH);
                lblBackground.setIcon(new javax.swing.ImageIcon(imgSkala));
            }
        } catch (Exception e) {
            System.out.println("Gagal memuat gambar: " + e.getMessage());
        }

        // Kode transparansi panel yang tadi (pastikan nama variabel sesuai)
        // Format: (Red, Green, Blue, Alpha) 
        // Alpha 0-255 (makin kecil makin transparan)   
        panelKiri.setBackground(new java.awt.Color(33, 33, 33, 200));        // Hitam transparan

        // Menambahkan waktu di panel Atas
        java.time.LocalDate tgl = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter format = java.time.format.DateTimeFormatter.ofPattern("dd MMM yyyy");
        lblTanggal.setText(tgl.format(format));
        
        // Menghilangkan background putih pada JTextArea
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0, 0)); 

        // Menghilangkan background dan border pada JScrollPane (wadahnya)
        paneText.setOpaque(false);
        paneText.getViewport().setOpaque(false);
        paneText.setBorder(null);
        paneText.setViewportBorder(null);
        
        // Atur skala/size
        aturSkala(instagramlogo, "/assets/instagram.png", 20, 20);
        aturSkala(anime, "/assets/kiriya aoi.png", 395, 533);
        
        // Menambah data dummy ke tabel
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();
    
        // BARIS SAKTI: Menghapus semua baris bawaan NetBeans yang kosong
        model.setRowCount(0); 

        // Baru kemudian isi data dummy
        model.addRow(new Object[]{"PC26001", "Asus", "Intel i5", "10000"});
        model.addRow(new Object[]{"PC26002", "Acer", "Intel i3", "8000"});
    }
    
    //*-----------------ini luar constructor
    
    private void pindahMenu(String namaKartu) {
        java.awt.CardLayout card = (java.awt.CardLayout) panelUtama.getLayout();
        card.show(panelUtama, namaKartu);
        panelUtama.revalidate();
        panelUtama.repaint();
    }
    
    //atur size gambar jLabel
    private void aturSkala(javax.swing.JLabel label, String path, int w, int h) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelKiri = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JLabel();
        btnPC = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JLabel();
        btnAlarm = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        panelMenuBeranda = new javax.swing.JPanel();
        instagramlogo = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        paneText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        anime = new javax.swing.JLabel();
        panelMenuPC = new javax.swing.JPanel();
        judulPC = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtMerek = new javax.swing.JTextField();
        txtProcessor = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPC = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPilih = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTarif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelMenuPelanggan = new javax.swing.JPanel();
        btnBeranda6 = new javax.swing.JLabel();
        btnBeranda8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMenuTransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelMenuAlarm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logowfo.png"))); // NOI18N
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, -1, -1));

        panelHeader.setBackground(new java.awt.Color(0, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(1000, 80));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblAlamat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setText("Jl. Antara Ada dan Tiada, Desa Air, Banjarmasin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date :");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(lblAlamat)
                .addGap(148, 148, 148)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlamat)
                .addGap(26, 26, 26))
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        panelKiri.setBackground(new java.awt.Color(153, 153, 153));

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_off.png"))); // NOI18N
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
        });

        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_off.png"))); // NOI18N
        btnPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPCMouseExited(evt);
            }
        });

        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_off.png"))); // NOI18N
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPelangganMouseExited(evt);
            }
        });

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_off.png"))); // NOI18N
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_off.png"))); // NOI18N
        btnAlarm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlarmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlarmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlarmMouseExited(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_logout_off.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBeranda, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                            .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAlarm)
                                .addComponent(btnLogout))
                            .addGap(24, 24, 24)))
                    .addComponent(btnPC)
                    .addComponent(btnPelanggan)
                    .addComponent(btnTransaksi))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBeranda)
                .addGap(18, 18, 18)
                .addComponent(btnPC)
                .addGap(18, 18, 18)
                .addComponent(btnPelanggan)
                .addGap(18, 18, 18)
                .addComponent(btnTransaksi)
                .addGap(55, 55, 55)
                .addComponent(btnAlarm)
                .addGap(67, 67, 67)
                .addComponent(btnLogout)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        getContentPane().add(panelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 620));

        panelUtama.setBackground(new java.awt.Color(63, 63, 63));
        panelUtama.setLayout(new java.awt.CardLayout());

        panelMenuBeranda.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instagramlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instagram.png"))); // NOI18N
        panelMenuBeranda.add(instagramlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 20, 20));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("SELAMAT DATANG!!");
        panelMenuBeranda.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 53, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Di sini menyediakan penyewaan PC dengan harga yang terjangkau se-Banjarmasin.\n\nMau :\n- Ngegame\n- Internetan\n- Nugas\n- Ngetik\ndan lain-lain.\n\nWFO tempatnya. Yuk ramaikan keseruanmu di sosial media, dan tag\n        @WarnetFO\n\nKami usahakan memberikan pelayanan yang terbaik. Anda sopan kami senang.\nTerima kasih\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        paneText.setViewportView(jTextArea1);

        panelMenuBeranda.add(paneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 103, 651, 348));
        panelMenuBeranda.add(anime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 395, 533));

        panelUtama.add(panelMenuBeranda, "menu_beranda");

        panelMenuPC.setBackground(new java.awt.Color(51, 51, 51));
        panelMenuPC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulPC.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        judulPC.setForeground(new java.awt.Color(255, 255, 255));
        judulPC.setText("DATA PC");
        panelMenuPC.add(judulPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 50));

        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/head.png"))); // NOI18N
        panelMenuPC.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID :");
        panelMenuPC.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 150, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Merek :");
        panelMenuPC.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Processor :");
        panelMenuPC.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        panelMenuPC.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, -1));

        txtMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMerekActionPerformed(evt);
            }
        });
        panelMenuPC.add(txtMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 250, -1));
        panelMenuPC.add(txtProcessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 250, -1));

        btnCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMenuPC.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 80, 30));

        btnDaftar.setBackground(new java.awt.Color(51, 102, 255));
        btnDaftar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/person_add.png"))); // NOI18N
        btnDaftar.setText("Daftar");
        btnDaftar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarMouseClicked(evt);
            }
        });
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        panelMenuPC.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, 150, 20));

        btnEdit.setBackground(new java.awt.Color(51, 102, 255));
        btnEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 231, 150, 20));

        btnHapus.setBackground(new java.awt.Color(51, 102, 255));
        btnHapus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buang.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 231, 150, 20));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Merek", "Processor", "Tarif"
            }
        ));
        tabelPC.setFillsViewportHeight(true);
        tabelPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPC);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 620, 150));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cari PC :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, -1));

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 20));

        panelMenuPC.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 660, 200));

        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihtr_off.png"))); // NOI18N
        btnPilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btnBatal.setBackground(new java.awt.Color(51, 102, 255));
        btnBatal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        panelMenuPC.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 231, 150, 20));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Tarif / jam :");
        panelMenuPC.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 150, -1));

        txtTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifActionPerformed(evt);
            }
        });
        txtTarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifKeyTyped(evt);
            }
        });
        panelMenuPC.add(txtTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        panelMenuPC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, 30));

        panelUtama.add(panelMenuPC, "menu_pc");

        panelMenuPelanggan.setBackground(new java.awt.Color(51, 51, 51));

        btnBeranda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihalarm_off.png"))); // NOI18N
        btnBeranda6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBeranda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pilihtr_off.png"))); // NOI18N
        btnBeranda8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PELANGGAN");

        javax.swing.GroupLayout panelMenuPelangganLayout = new javax.swing.GroupLayout(panelMenuPelanggan);
        panelMenuPelanggan.setLayout(panelMenuPelangganLayout);
        panelMenuPelangganLayout.setHorizontalGroup(
            panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                .addComponent(btnBeranda8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                .addGroup(panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnBeranda6))
                    .addGroup(panelMenuPelangganLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)))
                .addGap(0, 564, Short.MAX_VALUE))
        );
        panelMenuPelangganLayout.setVerticalGroup(
            panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPelangganLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addGroup(panelMenuPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBeranda6)
                    .addComponent(btnBeranda8))
                .addGap(111, 111, 111))
        );

        panelUtama.add(panelMenuPelanggan, "menu_pelanggan");

        panelMenuTransaksi.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRANSAKSI");

        javax.swing.GroupLayout panelMenuTransaksiLayout = new javax.swing.GroupLayout(panelMenuTransaksi);
        panelMenuTransaksi.setLayout(panelMenuTransaksiLayout);
        panelMenuTransaksiLayout.setHorizontalGroup(
            panelMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTransaksiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        panelMenuTransaksiLayout.setVerticalGroup(
            panelMenuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTransaksiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuTransaksi, "menu_transaksi");

        panelMenuAlarm.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALARM");

        javax.swing.GroupLayout panelMenuAlarmLayout = new javax.swing.GroupLayout(panelMenuAlarm);
        panelMenuAlarm.setLayout(panelMenuAlarmLayout);
        panelMenuAlarmLayout.setHorizontalGroup(
            panelMenuAlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAlarmLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        panelMenuAlarmLayout.setVerticalGroup(
            panelMenuAlarmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAlarmLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        panelUtama.add(panelMenuAlarm, "menu_alarm");

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 790, 620));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_beranda");
    }//GEN-LAST:event_btnBerandaMouseClicked

    private void btnPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_pc");
    }//GEN-LAST:event_btnPCMouseClicked

    private void btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_pelanggan");
    }//GEN-LAST:event_btnPelangganMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_transaksi");
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnAlarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseClicked
        // TODO add your handling code here:
        pindahMenu("menu_alarm");
    }//GEN-LAST:event_btnAlarmMouseClicked

    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered
        // TODO add your handling code here:
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnBeranda.repaint();
    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited
        // TODO add your handling code here:
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_beranda_off.png")));
        btnBeranda.repaint();
    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseEntered
        // TODO add your handling code here:
        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnPC.repaint();
    }//GEN-LAST:event_btnPCMouseEntered

    private void btnPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCMouseExited
        // TODO add your handling code here:
        btnPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pc_off.png")));
        btnPC.repaint();
    }//GEN-LAST:event_btnPCMouseExited

    private void btnPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseEntered
        // TODO add your handling code here:
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnPelanggan.repaint();
    }//GEN-LAST:event_btnPelangganMouseEntered

    private void btnPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseExited
        // TODO add your handling code here:
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_pelanggan_off.png")));
        btnPelanggan.repaint();
    }//GEN-LAST:event_btnPelangganMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        // TODO add your handling code here:
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnTransaksi.repaint();
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_off.png")));
        btnTransaksi.repaint();
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnAlarmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseEntered
        // TODO add your handling code here:
        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_on.png")));
        // Repaint memastikan gambar berubah instan tanpa jeda
        btnAlarm.repaint();
    }//GEN-LAST:event_btnAlarmMouseEntered

    private void btnAlarmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlarmMouseExited
        // TODO add your handling code here:
        btnAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_alarm_off.png")));
        btnAlarm.repaint();
    }//GEN-LAST:event_btnAlarmMouseExited

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerekActionPerformed

    private void tabelPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPCMouseClicked
        // TODO add your handling code here:
        int baris = tabelPC.getSelectedRow();
    
        // Penjaga: Jika baris yang diklik valid (bukan -1) 
        // dan datanya tidak kosong
        if (baris != -1 && tabelPC.getValueAt(baris, 0) != null) {
            try {
                txtID.setText(tabelPC.getValueAt(baris, 0).toString());
                txtMerek.setText(tabelPC.getValueAt(baris, 1).toString());
                txtProcessor.setText(tabelPC.getValueAt(baris, 2).toString());
                txtTarif.setText(tabelPC.getValueAt(baris, 3).toString());
            } catch (Exception e) {
                // Jika ada error tipe data, aplikasi tidak akan crash
                System.out.println("Error klik tabel: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_tabelPCMouseClicked

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseClicked
        // TODO add your handling code here:
        // Validasi: Cek apakah SEMUA field kosong (0/4)
        if (txtID.getText().isEmpty() && txtMerek.getText().isEmpty() && 
            txtProcessor.getText().isEmpty() && txtTarif.getText().isEmpty()) {

            // Jika 0/4 diisi, munculkan peringatan
            JOptionPane.showMessageDialog(this, "Minimal isi salah satu data (ID, Merek, Processor, atau Tarif)!", "Peringatan", JOptionPane.WARNING_MESSAGE);

        } else {
            // Jika minimal 1/4 diisi, data masuk ke tabel
            DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();
            model.addRow(new Object[]{
                txtID.getText(), 
                txtMerek.getText(), 
                txtProcessor.getText(), 
                txtTarif.getText()
            });

            JOptionPane.showMessageDialog(this, "Data PC Berhasil Didaftarkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Opsional: Kosongkan field setelah daftar agar bisa input data baru
            btnBatalMouseClicked(null); 
        }
    }//GEN-LAST:event_btnDaftarMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        int i = tabelPC.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();

        if (i >= 0) {
            model.setValueAt(txtID.getText(), i, 0);
            model.setValueAt(txtMerek.getText(), i, 1);
            model.setValueAt(txtProcessor.getText(), i, 2);
            model.setValueAt(txtTarif.getText(), i, 3);

            JOptionPane.showMessageDialog(this, "Data PC Berhasil Diperbarui!", "Update Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit di tabel terlebih dahulu!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        int i = tabelPC.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelPC.getModel();

        if (i >= 0) {
            // Tanya konfirmasi
            int tanya = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data PC ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (tanya == JOptionPane.YES_OPTION) {
                model.removeRow(i);
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus.");
                btnBatalMouseClicked(null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        txtID.setText("");
        txtMerek.setText("");
        txtProcessor.setText("");
        txtTarif.setText("");
        tabelPC.clearSelection();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnPilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMouseClicked
        // TODO add your handling code here:
        /*if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih data PC terlebih dahulu!");
        } else {
            // 1. Ambil data dari textfield
            String idTerpilih = txtID.getText();
            String tarifTerpilih = txtTarif.getText();

            // 2. Set ke Label di Laman Transaksi (Asumsi nama variabel label di Laman Transaksi)
            lblIDTransaksi.setText(idTerpilih);
            lblTarifTransaksi.setText(tarifTerpilih);

            // 3. Pindah ke Laman Transaksi
            java.awt.CardLayout card = (java.awt.CardLayout) panelUtama.getLayout();
            card.show(panelUtama, "kartu_transaksi");

            // Jangan lupa reset tombol sidebar agar sesuai menu yang aktif
            resetTombol();
            btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_transaksi_on.png")));
        }
        */
    }//GEN-LAST:event_btnPilihMouseClicked

    private void txtTarifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
    
        // Cek jika yang diketik bukan angka DAN bukan tombol hapus
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Hapus inputannya

            // Munculkan pesan peringatan
            JOptionPane.showMessageDialog(this, "Input salah! Kolom Tarif hanya boleh diisi dengan angka.", "Peringatan Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtTarifKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anime;
    private javax.swing.JLabel btnAlarm;
    private javax.swing.JButton btnBatal;
    private javax.swing.JLabel btnBeranda;
    private javax.swing.JLabel btnBeranda6;
    private javax.swing.JLabel btnBeranda8;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPC;
    private javax.swing.JLabel btnPelanggan;
    private javax.swing.JLabel btnPilih;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JLabel head;
    private javax.swing.JLabel instagramlogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel judulPC;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane paneText;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelMenuAlarm;
    private javax.swing.JPanel panelMenuBeranda;
    private javax.swing.JPanel panelMenuPC;
    private javax.swing.JPanel panelMenuPelanggan;
    private javax.swing.JPanel panelMenuTransaksi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tabelPC;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtProcessor;
    private javax.swing.JTextField txtTarif;
    // End of variables declaration//GEN-END:variables
}
