/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.components;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Sudirwo
 */
public class PCBox extends JPanel {

    /**
     * Creates new form PCBox
     */
    public PCBox(String kode, String tipe, String tarif, String status) {
        //?initComponents();
        setLayout(new GridLayout(4, 1));
        setBorder(BorderFactory.createLineBorder(Color.BLACK));
        setPreferredSize(new Dimension(180, 120));

        JLabel lblKode = new JLabel(kode, SwingConstants.CENTER);
        JLabel lblTipe = new JLabel(tipe, SwingConstants.CENTER);
        JLabel lblTarif = new JLabel("Rp " + tarif + "/jam", SwingConstants.CENTER);
        JLabel lblStatus = new JLabel(status, SwingConstants.CENTER);

        if (status.equalsIgnoreCase("Tersedia")) {
            lblStatus.setForeground(Color.GREEN);
        } else if (status.equalsIgnoreCase("Dipakai")) {
            lblStatus.setForeground(Color.RED);
        } else {
            lblStatus.setForeground(Color.GRAY);
        }

        add(lblKode);
        add(lblTipe);
        add(lblTarif);
        add(lblStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
