/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Sudirwo
 */
public class Beranda_item extends javax.swing.JPanel {

    /**
     * Creates new form Beranda_item
     */
    public Beranda_item() {
        initComponents();
        loadPCBoxes();
        
        
    }
    
    public void loadPCFromTable(DefaultTableModel model) {

        panelGrid.removeAll();

        for (int i = 0; i < model.getRowCount(); i++) {
            String kode = model.getValueAt(i, 0).toString();
            String tipe = model.getValueAt(i, 2).toString();
            String tarif = model.getValueAt(i, 3).toString();
            String status = model.getValueAt(i, 4).toString();

            PCBox box = new PCBox(kode, tipe, tarif, status);
            panelGrid.add(box);
        }

        panelGrid.revalidate();
        panelGrid.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelGrid = new javax.swing.JPanel();

        panelGrid.setLayout(new java.awt.GridLayout(10, 0, 4, 10));
        jScrollPane1.setViewportView(panelGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrid;
    // End of variables declaration//GEN-END:variables
}
